/* 
CIS 8040
Assignment 3
Hao Nguyen
Quan Le
Anirudh Chaudhary
 */

--CREATE TABLES

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL,
    FNAME VARCHAR(256) NOT NULL,
    LNAME VARCHAR(256) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    DOB DATE NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT NOT NULL,
    TYPE VARCHAR(256) NOT NULL,
    BALANCE DECIMAL(20,2) NOT NULL,
    FK_CUSTOMER INT NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_ID)
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT NOT NULL ,
    POSTED_DATE DATE NOT NULL,
    AMOUNT DECIMAL(20,2) NOT NULL,
    DESCRIPTION VARCHAR(256) NULL,
    FK_ACCOUNT INT NOT NULL,
    FK_STATEMENT INT NOT NULL,
    CONSTRAINT PK_TRANSACTION PRIMARY KEY(TRANSACTION_ID)
);

CREATE TABLE STATEMENT (
    STATEMENT_ID INT NOT NULL,
    BALANCE DECIMAL(20,2) NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    FK_ACCOUNT INT NOT NULL,
    CONSTRAINT PK_STATEMENT PRIMARY KEY(STATEMENT_ID)
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID INT NOT NULL,
    DATE_TIME TIMESTAMP(6) NOT NULL,
    NOTE VARCHAR(256) NULL,
    FK_CUSTOMER INT NOT NULL,
    FK_EMPLOYEE INT NOT NULL,
    FK_OFFICE INT NOT NULL,
    CONSTRAINT PK_APPOINTMENT PRIMARY KEY(APPOINTMENT_ID)
);

CREATE TABLE OFFICE (
    OFFICE_ID INT NOT NULL,
    ADDRESS1 VARCHAR(256) NOT NULL,
    ADDRESS2 VARCHAR(256) NULL,
    CITY VARCHAR(256) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP CHAR(6) NOT NULL,
    CONSTRAINT PK_OFFICE PRIMARY KEY(OFFICE_ID)
);

CREATE TABLE ADVISOR (
    EMPLOYEE_ID INT NOT NULL, 
    FNAME VARCHAR(256) NOT NULL, 
    LNAME VARCHAR(256) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    CONSTRAINT PK_ADVISOR PRIMARY KEY(EMPLOYEE_ID)
);


-- ALTER TABLE & CONSTRAINTS COMMANDS --

ALTER TABLE ACCOUNT
    ADD CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY(FK_CUSTOMER) REFERENCES CUSTOMER(CUSTOMER_ID);

    
ALTER TABLE TRANSACTION
    ADD CONSTRAINT FK_TRANSACTION_CUSTOMER FOREIGN KEY(FK_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE TRANSACTION
    ADD CONSTRAINT FK_TRANSACTION_STAEMENT FOREIGN KEY(FK_STATEMENT) REFERENCES STATEMENT(STATEMENT_ID);

    
ALTER TABLE STATEMENT
    ADD CONSTRAINT FK_STATEMENT_ACCOUNT FOREIGN KEY(FK_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_ID);

    
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT FK_APPOINT_CUSTOMER FOREIGN KEY(FK_CUSTOMER) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT FK_APPOINT_EMPLOYEE FOREIGN KEY(FK_EMPLOYEE) REFERENCES ADVISOR(EMPLOYEE_ID);
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT FK_APPOINT_OFFICE FOREIGN KEY(FK_OFFICE) REFERENCES OFFICE(OFFICE_ID);
     
-- End Of The File



